# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.2
    hooks:
      - id: terraform_fmt
        args: ["--args=-recursive"]
      - id: terraform_tflint
      - id: terraform_validate
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.18.0
    hooks:
      - id: terraform-docs-go
        args: [.]
  - repo: https://codeberg.org/frnmst/md-toc
    rev: 9.0.0
    hooks:
      - id: md-toc
        args: [-p, -s, "6", github]
