name: Lint, Validate & Test
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  lint-validate-test:
    name: Lint, Validate & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      - name: Terraform validate
        run: terraform validate
      - name: Terraform test
        run: terraform test
